pipeline {

    agent any

    environment {
        IMAGE_NAME = "neha-cicd-app"
        IMAGE_TAG = "v${BUILD_NUMBER}"
        NAMESPACE = "devops-app"
        DEPLOYMENT = "webapp"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Nehakolte/Internship_task.git'
            }
        }

        stage('Build') {
            steps {
                sh 'echo Building application...'
                sh 'docker build -t %IMAGE_NAME%:%IMAGE_TAG% .'
            }
        }

        stage('Test') {
            steps {
                sh 'echo Running application tests...'
                sh 'docker run --rm %IMAGE_NAME%:%IMAGE_TAG% nginx -t'
            }
        }

        stage('Docker Image') {
            steps {
                sh 'docker images %IMAGE_NAME%'
            }
        }

        stage('Load Image to Minikube') {
            steps {
                sh 'minikube image load %IMAGE_NAME%:%IMAGE_TAG%'
            }
        }

        stage('Deploy') {
            steps {
                sh 'kubectl apply -f k8s/namespace.yaml'
                sh 'kubectl apply -f k8s/service.yaml'
                sh 'kubectl set image deployment/%DEPLOYMENT% webapp=%IMAGE_NAME%:%IMAGE_TAG% -n %NAMESPACE%'
            }
        }

        stage('Rolling Deployment') {
            steps {
                sh 'kubectl rollout status deployment/%DEPLOYMENT% -n %NAMESPACE%'
            }
        }

        stage('Verify') {
            steps {
                sh 'kubectl get pods -n %NAMESPACE%'
                sh 'kubectl get deployment -n %NAMESPACE%'
            }
        }
    }

    post {
        success {
            echo 'CI/CD Pipeline completed successfully.'
        }

        failure {
            echo 'CI/CD Pipeline failed.'
        }
    }
}
